import { FormControl } from "@angular/forms";

// Definición de la interfaz Anime
export interface Anime {
  names: string[];
  audio: string;
  form?: FormControl;
  img?: string;
  video?: string;
}

export const animes: Anime[] = [
  { names: ["Yamada-kun to Lv999 no Koi wo Suru", "Yamada-kun to Lv999"], audio: "au_0" },
  { names: ["Hunter x Hunter"], audio: "au_1" },
  { names: ["Jujutsu Kaisen"], audio: "au_2" },
  { names: ["Shinseiki Evangelion", "Neon Genesis Evangelion"], audio: "au_3" },
  { names: ["Bishoujo Senshi Sailor Moon", "Sailor Moon"], audio: "au_4" },
  { names: ["Spy x Family"], audio: "au_5" },
  { names: ["Tokyo Revengers"], audio: "au_6" },
  { names: ["Cardcaptor Sakura"], audio: "au_7" },
  { names: ["Kimetsu no Yaiba"], audio: "au_8" },
  { names: ["Kusuriya no Hitorigoto"], audio: "au_9" },
  { names: ["Sousou no Frieren"], audio: "au_10" },
  { names: ["Toradora!"], audio: "au_11" },
  { names: ["One Piece"], audio: "au_12" },
  { names: ["Bakemonogatari"], audio: "au_13" },
  { names: ["Sword Art Online"], audio: "au_14" },
  { names: ["Shingeki no Kyojin", "Attack on Titan"], audio: "au_15" },
  { names: ["Oshi no Ko"], audio: "au_16" },
  { names: ["Noragami"], audio: "au_17" },
  { names: ["Overlord"], audio: "au_18" },
  { names: ["Re:Zero kara Hajimeru Isekai Seikatsu", "Re:Zero"], audio: "au_19" },
  { names: ["Mushoku Tensei: Isekai Ittara Honki Dasu", "Mushoku Tensei: Jobless Reincarnation"], audio: "au_20" },
  { names: ["No Game No Life"], audio: "au_21" },
  { names: ["Doraemon"], audio: "au_22" },
  { names: ["Digimon", "Digimon 02"], audio: "au_23" },
  { names: ["Pokemon"], audio: "au_24" },
  { names: ["Slayers"], audio: "au_25" },
  { names: ["Naruto"], audio: "au_26" },
  { names: ["Naruto Shippuden", "Naruto: Shippuden"], audio: "au_27" },
  { names: ["Jigokuraku", "Hell's Paradise"], audio: "au_28" },
  { names: ["Undead Unluck"], audio: "au_29" },
  { names: ["Tengoku Daimakyou"], audio: "au_30" },
  { names: ["Dragon Ball", "As bolas maxicas", "As bolas máxicas"], audio: "au_31" },
  { names: ["Dragon Ball Z"], audio: "au_32" },
  { names: ["Dragon Ball GT"], audio: "au_33" },
  { names: ["Death Parade"], audio: "au_34" },
  { names: ["Death Note"], audio: "au_35" },
  { names: ["Parasyte", "Kiseijuu: Sei no Kakuritsu"], audio: "au_36" },
  { names: ["Fullmetal Alchemist"], audio: "au_37" },
  { names: ["Fullmetal Alchemist: Brotherhood"], audio: "au_38" },
  { names: ["Tokyo Ghoul"], audio: "au_39" },
  { names: ["Dr Stone", "Dr. Stone"], audio: "au_40" },
  { names: ["Black Clover"], audio: "au_41" },
  { names: ["Bleach"], audio: "au_42" },
  { names: ["Erased", "Boku dake ga Inai Machi"], audio: "au_43" },
  { names: ["Enen no Shouboutai", "Fire Force"], audio: "au_44" },
  { names: ["JoJo no Kimyou na Bouken", "JoJo's Bizarre Adventure"], audio: "au_45" },
  { names: ["Cowboy Bebop"], audio: "au_46" },
  { names: ["Beastars"], audio: "au_47" },
  { names: ["Chainsaw Man"], audio: "au_48" },
  { names: ["Boruto"], audio: "au_49" },
  { names: ["Code Geass", "Code Geass: Hangyaku no Lelouch"], audio: "au_50" },
  { names: ["Domestic na Kanojo", "Domestic Girlfriend"], audio: "au_51" },
  { names: ["InuYasha"], audio: "au_52" },
  { names: ["Gokudou-kun Manyuuki", "Jester: El Aventurero", "Jester el aventurero"], audio: "au_53" },
  { names: ["Kaguya-sama wa Kokurasetai: Tensai-tachi no Renai Zunousen", "Kaguya-sama: Love is War", "Kaguya-sama"], audio: "au_54" },
  { names: ["Komi-san wa, Comyushou desu.", "Komi Can't Communicate", "Komi-san"], audio: "au_55" },
  { names: ["Mashle", "Mashle: Magic and Muscles"], audio: "au_56" },
  { names: ["Mirai Nikki", "The Future Diary"], audio: "au_57" },
  { names: ["Mob Psycho 100"], audio: "au_58" },
  { names: ["Boku no Hero Academia", "My Hero Academia"], audio: "au_59" },
  { names: ["One Punch Man"], audio: "au_60" },
  { names: ["Paripi Koumei", "Ya Boy Kongming!"], audio: "au_61" },
  { names: ["Ousama Ranking", "Ranking of Kings"], audio: "au_62" },
  { names: ["Yakusoku no Neverland", "The Promised Neverland"], audio: "au_63" },
  { names: ["Tate no Yuusha no Nariagari", "The Rising of the Shield Hero"], audio: "au_64" },
  { names: ["Fumetsu no Anata e", "To Your Eternity"], audio: "au_65" },
  { names: ["Urusei Yatsura", "Lum, la chica invasora"], audio: "au_66" },
  { names: ["Shigatsu wa Kimi no Uso", "Your Lie in April"], audio: "au_67" },
  { names: ["Yu Yu Hakusho"], audio: "au_68" },
  { names: ["Yuri!!! on Ice"], audio: "au_69" },
  { names: ["Zom 100: Zombie ni Naru made ni Shitai 100 no Koto", "Zom 100: Bucket List of the Dead", "Zom 100"], audio: "au_70" },
  { names: ["Gintama"], audio: "au_71" },
  { names: ["Nanatsu no Taizai"], audio: "au_72" },
  { names: ["Fairy Tail"], audio: "au_73" },
  { names: ["Dororo"], audio: "au_74" },
  { names: ["Dragon Ball Super"], audio: "au_75" },
  { names: ["Fate/stay night", "Fate/stay night: Unlimited Blade Works", "Fate stay night"], audio: "au_76" },
  { names: ["Horimiya"], audio: "au_77" },
  { names: ["Kakegurui"], audio: "au_78" },
  { names: ["KonoSuba", "Kono Subarashii Sekai ni Shukufuku wo!"], audio: "au_79" },
  { names: ["Made in Abyss"], audio: "au_80" },
  { names: ["Kanojo, Okarishimasu", "Rent a Girlfriend", "Kanojo Okarishimasu"], audio: "au_81" },
  { names: ["Steins;Gate"], audio: "au_82" },
  { names: ["Vinland Saga"], audio: "au_83" },
  { names: ["Akame ga Kill!"], audio: "au_84" },
  { names: ["Tengen Toppa Gurren Lagann", "Gurren Lagann"], audio: "au_85" },
  { names: ["Sakurasou no Pet na Kanojo"], audio: "au_86" },
  { names: ["Ansatsu Kyoushitsu", "Assassination Classroom"], audio: "au_87" },
  { names: ["Elfen Lied"], audio: "au_88" },
  { names: ["Shokugeki no Souma", "Food Wars!"], audio: "au_89" },
  { names: ["Gangsta", "Gangsta."], audio: "au_90" },
  { names: ["Rurouni Kenshin: Meiji Kenkaku Romantan", "Rurouni Kenshin"], audio: "au_91" },
  { names: ["Saint Seiya", "Los Caballeros del Zodiaco"], audio: "au_92" },
  { names: ["Solo Leveling", "Ore dake Level Up na Ken"], audio: "au_93" },
  { names: ["Sono Bisque Doll wa Koi wo Suru"], audio: "au_94" },
  { names: ["Soul Eater"], audio: "au_95" },
  { names: ["Violet Evergarden"], audio: "au_96" },
  { names: ["Dorohedoro"], audio: "au_97" },
  { names: ["Puella Magi Madoka Magica", "Mahou Shoujo Madoka Magica"], audio: "au_98" },
  { names: ["Kill la Kill"], audio: "au_99" },
  { names: ["Blue Lock"], audio: "au_100" },
  { names: ["Goblin Slayer"], audio: "au_101" },
  { names: ["Bocchi the Rock!"], audio: "au_102" },
  { names: ["Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e", "Classroom of the Elite"], audio: "au_103" },
  { names: ["Bishounen Tanteidan", "Pretty Boy Detective Club"], audio: "au_104" },
  { names: ["Mairimashita! Iruma-kun", "Welcome to Demon School! Iruma-kun"], audio: "au_105" },
  { names: ["Haikyuu!!", "Haikyu!! Los Ases del Vóley"], audio: "au_106" },
  { names: ["Sentai Daishikkaku", "Go! Go! Loser Ranger!"], audio: "au_107" },
  { names: ["Kaijuu 8-gou", "Kaiju No. 8"], audio: "au_108" },
  { names: ["Blend S", "Blend-S"], audio: "au_109" },
  { names: ["Oliver y Benji", "Captain Tsubasa"], audio: "au_110" },
  { names: ["Houseki no Kuni", "Land of the Lustrous"], audio: "au_111" },
  { names: ["Inuyashiki", "Inuyashiki: Last Hero"], audio: "au_112" },
  { names: ["Shinsekai Yori"], audio: "au_113" },
  { names: ["Inu x Boku SS", "Inu x Boku Secret Service"], audio: "au_114" },
  { names: ["Bokusatsu Tenshi Dokuro-chan", "Bludgeoning Angel Dokuro-chan"], audio: "au_115" },
  { names: ["Charlotte"], audio: "au_116" },
  { names: ["Bungou Stray Dogs", "Bungo Stray Dogs"], audio: "au_117" },
  { names: ["Chobits"], audio: "au_118" },
  { names: ["Toaru Majutsu no Index", "A Certain Magical Index"], audio: "au_119" }
];
